#' Tidy intensities generated by algorithm so that lights can accept them
#'
#' @param intensities_matrix Matrix of predicted intensities
#' @inheritParams internal.calibCombine
#'
#' @return Maxtrix of intensities which are integers and capped at the maximum possible intensity
#'
#' @examples
#'
#' # Generate untidy intensities
#' intensities = matrix(runif(n=10*8, min=-1, max=1020), nrow=8)
#' print(intensities)
#'
#' # Get vector of unique calibration intensities
#' calib = unique(LightFitR::calibration$intensity)
#' print(calib)
#'
#' # Run function
#'
#' internal.tidyIntensities(intensities, calib)
#'
internal.tidyIntensities = function(intensities_matrix, calibration_intensities){

  # Round, since the lights only accept integers
  internalMat = round(intensities_matrix)

  # Cap the intensities at maximum intensity of calibration
  maxAllowable = max(calibration_intensities)

  overAllowable = which(internalMat > maxAllowable)
  internalMat[overAllowable] = maxAllowable

  # Set negatives to 0
  under0 = which(internalMat < 0)
  internalMat[under0] = 0

  # Return
  return(internalMat)
}
