#' Write regime matrix to csv file that is readable by the Heliospectra light system
#'
#' @param regime_matrix Matrix containing light regime, as generated by makeRegime
#' @param filename Character. Filename to export to
#'
#' @return Table that was exported
#' @export CSV file that is readable by Heliospectra lights
#'
#' @examples
write.helio_csv = function(regime_matrix, filename){
  helio.checkFormat(regime_matrix[-c(1:4),])

  # Header
  header = matrix(nrow=3, ncol=10)
  header[1,] = c('Schedule.exported.from', filename, rep('', 8))
  header[2,] = c('Lamp timestamp', format(sys.time(), "%Y-%m-%d %H:%M:%S"), rep('', 8))
  header[3,] = c('', helio.dyna.leds$name)

  # Schedule
  schedule = t(regime_matrix[-c(2:4),])

  # Rbind and export
  csv = rbind(header, schedule)
  write.csv(csv, file=filename, sep=';', row.names=FALSE, col.names=FALSE)
  return(csv)
}
