#' Write the schedule to file that Heliospectra can parse
#'
#' @param regime_matrix Matrix containing light regime, as generated by makeRegime
#' @param filename Character. Filename to export to
#' @param format Character. Which format to export to? csv or json. Use extensions '.csv' or '.txt'
#'
#' @return
#' @export File (format specified by user) that is readable by Heliospectra Lights
#'
#' @examples
helio.writeSchedule = function(regime_matrix, filename, format=c('csv', 'json')){
  if(format=='csv'){
    csv = helio.csv_schedule(regime_matrix, filename)
    write.table(csv, file=filename, row.names=F, col.names=F, sep=';', quote=F)
  }

  if(format=='json'){
    json = helio.json_schedule(regime_matrix, filename)
    write.table(json, file=filename, row.names = F, col.names = F, quote = F)
  }
}
